# Generated by Django 5.1.3 on 2025-10-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutsection',
            old_name='page',
            new_name='about_page',
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
