# Generated by Django 5.2.7 on 2025-11-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_queueentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='name',
            field=models.CharField(default='Guest', max_length=100),
        ),
    ]
