# Generated by Django 5.2.7 on 2025-11-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_queueentry_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reset', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
