# Generated by Django 5.2.7 on 2025-11-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_queueresetlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.CharField(max_length=20)),
                ('served_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
