# Generated by Django 5.2.7 on 2025-11-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_queuerepository'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='selected_service',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='queuerepository',
            name='selected_service',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
