# Generated by Django 5.2.7 on 2025-11-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_queueentry_age_queueentry_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='about/sections/'),
        ),
    ]
